### ISSUE TITLE
Problem with Migrating fron NoahBres MeepMeep

### ISSUE THREAD

**Issue by Stephen-Onochie** [rh-robotics/MeepMeep#10]
Hi there,
I am trying to migrate from the Noahbres version of MeepMeep but despite following the guide, I am not getting the needed classes to properly code. Is there something I'm doing wrong?

<img width="1408" alt="Screenshot 2024-09-26 at 5 11 08 PM" src="https://github.com/user-attachments/assets/eb71e096-2208-4ade-918b-7e272b45293f">
<img width="1408" alt="Screenshot 2024-09-26 at 5 10 43 PM" src="https://github.com/user-attachments/assets/1ce0202e-2359-4e70-bf0d-5d6bcfb2fb41">

**Comment by rowan-mcalpin** [comment]
Change the import statements from `com.noahbres` to `org.rowlandhall`

**Comment by DragonDev07** [comment]
Yep, what @rowan-mcalpin said should do the trick. Its step 4 in the migration guide :D

**Comment by Stephen-Onochie** [comment]
Yes, I forgot to mention that even if I change the import statements, I still can't access the new version of MeepMeep. Is there any files I can send to help you all find my problem?

<img width="496" alt="Screenshot 2024-09-27 at 8 26 20 AM" src="https://github.com/user-attachments/assets/f0272494-94fc-4f67-b413-44b745fa5c0b">

**Comment by Stephen-Onochie** [comment]
Thank you all for the support. For some reason, the Java version in my build gradle file was `JavaVersion.VERSION_1_8`. I just changed it to `JavaVersion.VERSION_17` and now everything works.

<img width="583" alt="Java Version" src="https://github.com/user-attachments/assets/a0e2bb05-13a9-4ea8-858c-1cc87f0a56cb">

**Comment by DragonDev07** [comment]
Glad you got it sorted out!
