### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by NikhilKonduru8** [rh-robotics/MeepMeep#15]
I am getting the error below when I try to run the meep meep testing file. What can I do to fix this. 
      
      A problem occurred configuring project ':FtcRobotController'.
      >                     defaultConfig contains custom BuildConfig fields, but the feature is disabled.
                            To enable the feature, add the following to your module-level build.gradle:
        `android.buildFeatures.buildConfig true`
      
      
      > un with --stacktrace option to get the stack trace.
      > Run with --info or --debug option to get more log output.
      > Run with --scan to get full insights.
      > Get more help at https://help.gradle.org.

**Comment by rowan-mcalpin** [comment]
Have you tried adding `android.buildFeatures.buildConfig true` to your TeamCode/build.gradle file?

**Comment by DragonDev07** [comment]
Closing due to a month of inactivity.
