### ISSUE TITLE
DefaultBotBuilder followTrajectorySequence is private

### ISSUE THREAD

**Issue by rowan-mcalpin** [rh-robotics/MeepMeep#5]
![image](https://github.com/user-attachments/assets/8fb0d83d-e9fc-4bc0-a6cb-44975d274847)

This worked in the latest NoahBres MeepMeep:
![image](https://github.com/user-attachments/assets/35a09ee1-be46-4a77-8f46-a2e4adef49e7)

But it is no longer working.

**Comment by DragonDev07** [comment]
Would you mind posting how you are calling this? It seems to be working on my end, and this section of the code is no different from the NoahBres repository!
